#!/bin/bash

/bin/chmod 777 /var/www/bootstrap -Rf
/bin/chmod 777 /var/www/storage -Rf

/usr/bin/vault agent -config=/etc/vault-agent/agent-config-one-execution.hcl -log-level=debug

/usr/bin/php /var/www/artisan doctrine:generate:proxies
/usr/bin/php /var/www/artisan migrate --force

/bin/chmod 777 /var/www/bootstrap -Rf
/bin/chmod 777 /var/www/storage -Rf

/usr/bin/php /var/www/artisan db:seed --force
/usr/bin/php /var/www/artisan storage:link
