<?php

namespace DoctrineProxies\__CG__\App\Packages\Empresa\Domain\Model;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \App\Packages\Empresa\Domain\Model\Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'user', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'cartaoCnpj', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'cadastradaEm', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'cnpj', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'razaoSocial', 'createdAt', 'updatedAt', 'deletedAt', 'id'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'user', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'cartaoCnpj', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'cadastradaEm', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'cnpj', '' . "\0" . 'App\\Packages\\Empresa\\Domain\\Model\\Empresa' . "\0" . 'razaoSocial', 'createdAt', 'updatedAt', 'deletedAt', 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUser(): \App\Packages\User\Domain\Model\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpj(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpj', []);

        return parent::getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function getRazaoSocial(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazaoSocial', []);

        return parent::getRazaoSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function concluirCadastro(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'concluirCadastro', []);

        parent::concluirCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function getCadastradaEm(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCadastradaEm', []);

        return parent::getCadastradaEm();
    }

    /**
     * {@inheritDoc}
     */
    public function createCartaoCnpj(array $dados): \App\Packages\Empresa\CartaoCnpj\Domain\Model\CartaoCnpj
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createCartaoCnpj', [$dados]);

        return parent::createCartaoCnpj($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartaoCnpj(): \App\Packages\Empresa\CartaoCnpj\Domain\Model\CartaoCnpj
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartaoCnpj', []);

        return parent::getCartaoCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt(\DateTime $deletedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
